package com.calmdown.mobilePay.domain.pay;

public enum StatusCode {
    CERT_READY, CERT_SUCCESS, CERT_FAILURE,
    AUTH_READY, AUTH_SUCCESS, AUTH_FAILURE,
    CANCEL_READY, CANCEL_SUCCESS, CANCEL_FAIL,
    SMS_CHECK_READY, SMS_CHECK_SUCCESS, SMS_CHECK_FAILURE
}
